package com.erhsh.prj.distrmgmtsys.model;

// Generated 2015-8-5 23:30:11 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CarInfo generated by hbm2java
 */
@Entity
@Table(name = "car_info", catalog = "distrmgmtsys")
public class CarInfo implements java.io.Serializable {

	private Long carId;
	private String id;
	private String brand;
	private String factory;
	private String type;
	private String system;
	private String systemId;
	private String title;
	private String engine;
	private BigDecimal guidePrice;
	private String size;
	private String structure;
	private String gearBox;
	private String speed;
	private String acceleration;
	private String oilConsumption;
	private String webLink;

	public CarInfo() {
	}

	public CarInfo(String id, String brand, String factory, String type,
			String system, String systemId, String title, String engine,
			BigDecimal guidePrice, String size, String structure,
			String gearBox, String speed, String acceleration,
			String oilConsumption, String webLink) {
		this.id = id;
		this.brand = brand;
		this.factory = factory;
		this.type = type;
		this.system = system;
		this.systemId = systemId;
		this.title = title;
		this.engine = engine;
		this.guidePrice = guidePrice;
		this.size = size;
		this.structure = structure;
		this.gearBox = gearBox;
		this.speed = speed;
		this.acceleration = acceleration;
		this.oilConsumption = oilConsumption;
		this.webLink = webLink;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAR_ID", unique = true, nullable = false)
	public Long getCarId() {
		return this.carId;
	}

	public void setCarId(Long carId) {
		this.carId = carId;
	}

	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "BRAND")
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "FACTORY")
	public String getFactory() {
		return this.factory;
	}

	public void setFactory(String factory) {
		this.factory = factory;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "SYSTEM", length = 10)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "SYSTEM_ID", length = 0)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "ENGINE")
	public String getEngine() {
		return this.engine;
	}

	public void setEngine(String engine) {
		this.engine = engine;
	}

	@Column(name = "GUIDE_PRICE", precision = 10)
	public BigDecimal getGuidePrice() {
		return this.guidePrice;
	}

	public void setGuidePrice(BigDecimal guidePrice) {
		this.guidePrice = guidePrice;
	}

	@Column(name = "SIZE")
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "STRUCTURE")
	public String getStructure() {
		return this.structure;
	}

	public void setStructure(String structure) {
		this.structure = structure;
	}

	@Column(name = "GEAR_BOX")
	public String getGearBox() {
		return this.gearBox;
	}

	public void setGearBox(String gearBox) {
		this.gearBox = gearBox;
	}

	@Column(name = "SPEED")
	public String getSpeed() {
		return this.speed;
	}

	public void setSpeed(String speed) {
		this.speed = speed;
	}

	@Column(name = "ACCELERATION")
	public String getAcceleration() {
		return this.acceleration;
	}

	public void setAcceleration(String acceleration) {
		this.acceleration = acceleration;
	}

	@Column(name = "OIL_CONSUMPTION")
	public String getOilConsumption() {
		return this.oilConsumption;
	}

	public void setOilConsumption(String oilConsumption) {
		this.oilConsumption = oilConsumption;
	}

	@Column(name = "WEB_LINK")
	public String getWebLink() {
		return this.webLink;
	}

	public void setWebLink(String webLink) {
		this.webLink = webLink;
	}

}
