package com.erhsh.prj.distrmgmtsys.model;

// Generated 2015-8-5 23:30:11 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderItemId generated by hbm2java
 */
@Embeddable
public class OrderItemId implements java.io.Serializable {

	private long orderId;
	private long orderSeqNumId;

	public OrderItemId() {
	}

	public OrderItemId(long orderId, long orderSeqNumId) {
		this.orderId = orderId;
		this.orderSeqNumId = orderSeqNumId;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "ORDER_SEQ_NUM_ID", nullable = false)
	public long getOrderSeqNumId() {
		return this.orderSeqNumId;
	}

	public void setOrderSeqNumId(long orderSeqNumId) {
		this.orderSeqNumId = orderSeqNumId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderItemId))
			return false;
		OrderItemId castOther = (OrderItemId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getOrderSeqNumId() == castOther.getOrderSeqNumId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getOrderId();
		result = 37 * result + (int) this.getOrderSeqNumId();
		return result;
	}

}
