package com.erhsh.prj.distrmgmtsys.model;

// Generated 2015-8-5 23:30:11 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_status", catalog = "distrmgmtsys")
public class OrderStatus implements java.io.Serializable {

	private Integer orderStatusId;
	private String statusName;

	public OrderStatus() {
	}

	public OrderStatus(String statusName) {
		this.statusName = statusName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_STATUS_ID", unique = true, nullable = false)
	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "STATUS_NAME")
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
