package com.erhsh.prj.distrmgmtsys.model;

// Generated 2015-8-5 23:30:11 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "order_item", catalog = "distrmgmtsys")
public class OrderItem implements java.io.Serializable {

	private OrderItemId id;
	private Long carInfoId;
	private Long userId;
	private Long contractId;
	private Long orderPrice;

	public OrderItem() {
	}

	public OrderItem(OrderItemId id) {
		this.id = id;
	}

	public OrderItem(OrderItemId id, Long carInfoId, Long userId,
			Long contractId, Long orderPrice) {
		this.id = id;
		this.carInfoId = carInfoId;
		this.userId = userId;
		this.contractId = contractId;
		this.orderPrice = orderPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderId", column = @Column(name = "ORDER_ID", nullable = false)),
			@AttributeOverride(name = "orderSeqNumId", column = @Column(name = "ORDER_SEQ_NUM_ID", nullable = false)) })
	public OrderItemId getId() {
		return this.id;
	}

	public void setId(OrderItemId id) {
		this.id = id;
	}

	@Column(name = "CAR_INFO_ID")
	public Long getCarInfoId() {
		return this.carInfoId;
	}

	public void setCarInfoId(Long carInfoId) {
		this.carInfoId = carInfoId;
	}

	@Column(name = "USER_ID")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "CONTRACT_ID")
	public Long getContractId() {
		return this.contractId;
	}

	public void setContractId(Long contractId) {
		this.contractId = contractId;
	}

	@Column(name = "ORDER_PRICE", precision = 10, scale = 0)
	public Long getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(Long orderPrice) {
		this.orderPrice = orderPrice;
	}

}
